language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - composer self-update
  - php artisan key:generate
  
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE tfgjgg_test;'
  - echo "memory_limit=512M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -u root tfgjgg_test < inicioBBDD.sql
script:
  - phpunit

services:
  - mysql

notifications: 
  email: false