language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - composer self-update
  - php artisan key:generate
  - mysql -u root < inicioBBDD.sql
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE tfgjgg_test;'

script:
  - phpunit

services:
  - mysql

notifications: 
  email: false