language: php

php:
  - 7.1.33

before_script:
  - rm -r vendor
  - rm composer.lock
  - rm -r TFG_Cliente_new
  - composer clearcache
  - cp .env.travis .env
  - npm install
  - composer install

  

before_install:
  - mysql -e 'CREATE DATABASE tfgjgg_test2;'
  - echo "memory_limit=512M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -u root tfgjgg_test2 < inicioBBDD.sql
script:
  - phpunit  

services:
  - mysql

notifications: 
  email: false